-- Step 1: Create Database
CREATE DATABASE DDL;
GO
USE DDL;
GO

-- Step 2: Create TRG_DEPT Table
CREATE TABLE TRG_DEPT (ID INT PRIMARY KEY, NAME VARCHAR(25));
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRG_DEPT';

-- Step 3: Create DEPARTMENTS Table and Insert Data
CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(50)
);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (1, 'CSE'), (2, 'EEE'), (3, 'ECE');
SELECT * FROM DEPARTMENTS;

-- Step 4: Create TRG_EMP Table
CREATE TABLE TRG_EMP (
    ID INT,  
    LAST_NAME VARCHAR(25), 
    FIRST_NAME VARCHAR(25), 
    DEPT_ID INT  
);

-- Step 5: Modify Column in TRG_EMP
ALTER TABLE TRG_EMP  
ALTER COLUMN LAST_NAME VARCHAR(50);

-- Step 6: Create EMPLOYEES Table and Insert Data
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    DEPARTMENT_ID INT
);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID)
VALUES 
    (1, 'Lohitha', 'Suggala', 50000.00, 1),
    (2, 'Saritha', 'Marri', 60000.00, 2),
    (3, 'Yogitha', 'Chava', 65000.00, 1);
    
-- Step 7: Copy Data from EMPLOYEES to TRG_EMPLOYEES Table
SELECT EMPLOYEE_ID AS ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID AS DEPT_ID  
INTO TRG_EMPLOYEES  
FROM EMPLOYEES;
SELECT * FROM TRG_EMPLOYEES;

-- Step 8: Drop TRG_EMP Table
DROP TABLE TRG_EMP;

-- Step 9: Rename TRG_EMPLOYEES to TRG_EMP (Fixed Syntax)
EXEC sp_rename 'TRG_EMPLOYEES', 'TRG_EMP';

-- Step 10: Drop Column FIRST_NAME from TRG_EMP
ALTER TABLE TRG_EMP DROP COLUMN FIRST_NAME;
