-- 1. Display Orders Issued by Salesman 'Paul Adam'
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id = (SELECT salesman_id FROM Salesman WHERE name = 'Paul Adam');

-- 2. Display Orders Generated by London-Based Salespeople
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE city = 'London');
GO

-- 3. Display Orders from Salespeople Handling Customer ID 3007
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Customer WHERE customer_id = 3007);
GO

-- 4. Display Orders Exceeding Average Value on 10-Oct-2012
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE ord_date = '2012-10-10' 
AND purch_amt > (SELECT AVG(purch_amt) FROM Orders WHERE ord_date = '2012-10-10');
GO

-- 5. Display Orders Generated in New York City
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE city = 'New York');
GO

-- 6. Display Commission of Salespeople in Paris
SELECT commission FROM Salesman WHERE city = 'Paris';
GO

-- 7. Display Customers with ID Below 2001 Under Salesperson Mc Lyon
SELECT * FROM Customer 
WHERE customer_id < 2001 
AND salesman_id = (SELECT salesman_id FROM Salesman WHERE name = 'Mc Lyon');
GO

-- 8. Count of Customers with Above-Average Grades in New York City
SELECT grade, COUNT(*) AS customer_count 
FROM Customer 
WHERE city = 'New York' 
AND grade > (SELECT AVG(grade) FROM Customer) 
GROUP BY grade;
GO

-- 9. Display Orders of Salespeople with Maximum Commission
SELECT ord_no, purch_amt, ord_date, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE commission = (SELECT MAX(commission) FROM Salesman));
GO

-- 10. Display Customers Who Placed Orders on 17th August 2012
SELECT O.ord_no, O.purch_amt, O.ord_date, O.customer_id, O.salesman_id, C.cust_name 
FROM Orders O 
JOIN Customer C ON O.customer_id = C.customer_id 
WHERE O.ord_date = '2012-08-17';
GO
